# Generated by Django 4.2.1 on 2023-05-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
